[tool.poetry]
name = "audio-shap-bachelor"
version = "0.1.0"
description = "Bachelor work code"
authors = ["Paweł Pozorski <pozorski.paul@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pre-commit = "^4.3.0"
black = "^25.9.0"
flake8 = "^7.3.0"
isort = "^6.1.0"
autoflake = "^2.3.1"
pylint = "^3.3.8"
bandit = "^1.8.6"
mypy = "^1.18.2"
nbqa = "^1.9.1"
datasets = "<4.0.0"
jupyter = "^1.1.1"
ipywidgets = "^8.1.7"
torch = "^2.8.0"
torchcodec = "^0.7.0"
librosa = "^0.11.0"
soundfile = "^0.13.1"
transformers = "4.50"
lingua-language-detector = "^2.1.1"
matplotlib = "^3.10.6"
pydantic = "^2.11.10"
nltk = "^3.9.2"
types-pygments = "^2.19.0.20250809"
types-colorama = "^0.4.15.20250801"
types-decorator = "^5.2.0.20250324"
types-jsonschema = "^4.25.1.20250822"
types-pexpect = "^4.9.0.20250916"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
