[tool.poetry]
name = "mllm-shap"
version = "0.1.0"
description = "Shap implementation for Multi Modal Large Language Models with audio and text on input."
authors = ["Paweł Pozorski <pozorski.paul@gmail.com>"]
readme = "README.md"
packages = [{include = "mllm_shap", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
