name: Pytest mllm_shapx

on:
  push:
    branches:
      - main
    paths:
      - "experiments/mllm_shapx/**"
  pull_request:
    branches:
      - main
    paths:
      - "experiments/mllm_shapx/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Sync deps
        run: make install

      - name: Run mllm_shapx tests
        run: make tests-mllm-shapx
